import json
import os
from typing import Any, Dict, List, Optional

import requests

from utils.config import settings
from utils.helpers import console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.table import Table

AGENT1_SYSTEM_PROMPT = (
    "You are a code generation agent. Your task is to generate Python code based on task descriptions.\n"
    "\n"
    "You MUST output ONLY valid JSON in the following format:\n"
    "{\n"
    '  "code": "the Python code here",\n'
    '  "explanation": "brief explanation of your approach",\n'
    '  "task_description": "what the code does"\n'
    "}\n"
    "\n"
    "Rules:\n"
    "1. Output ONLY the JSON object (no prose, no markdown code blocks, no backticks).\n"
    "2. Use double quotes for all keys and strings.\n"
    "3. Escape newlines in the code string using \\n.\n"
    "4. The code should be complete and functional.\n"
    "5. Include proper error handling where appropriate.\n"
)

AGENT2_SYSTEM_PROMPT = (
    "You are a code validation and improvement agent. Your task is to review code generated by another agent, "
    "validate it, identify issues, and provide an improved version.\n"
    "\n"
    "You MUST output ONLY valid JSON in the following format:\n"
    "{\n"
    '  "is_valid": true or false,\n'
    '  "issues": ["issue 1", "issue 2", ...],\n'
    '  "improved_code": "the improved Python code here",\n'
    '  "improvements": ["improvement 1", "improvement 2", ...],\n'
    '  "validation_notes": "detailed validation comments"\n'
    "}\n"
    "\n"
    "Rules:\n"
    "1. Output ONLY the JSON object (no prose, no markdown code blocks, no backticks).\n"
    "2. Use double quotes for all keys and strings.\n"
    "3. Escape newlines in code strings using \\n.\n"
    "4. Check for: correctness, edge cases, efficiency, code quality, best practices.\n"
    "5. Always provide improved_code even if the original is valid (can be the same or improved).\n"
    "6. If no issues found, set issues to an empty array.\n"
)


def _build_headers(api_key: str) -> Dict[str, str]:
    return {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }


def _get_base_url() -> str:
    return os.getenv("OPENAI_BASE_URL", "https://api.openai.com")


def _build_payload(
    model: str,
    messages: List[Dict[str, str]],
    temperature: float,
) -> Dict[str, Any]:
    return {
        "model": model,
        "messages": messages,
        "temperature": temperature,
    }


def _post_chat_completions(
    base_url: str,
    api_key: str,
    payload: Dict[str, Any],
    timeout_seconds: float = 30.0,
) -> Dict[str, Any]:
    url = f"{base_url.rstrip('/')}/v1/chat/completions"
    headers = _build_headers(api_key)
    response = requests.post(url, headers=headers, json=payload, timeout=timeout_seconds)
    response.raise_for_status()
    return response.json()


def _extract_message_content(body: Dict[str, Any]) -> str:
    try:
        return (body["choices"][0]["message"]["content"] or "").strip()
    except Exception:
        return ""


def _call_agent(
    system_prompt: str,
    user_message: str,
    temperature: float,
    model: str,
    base_url: str,
    api_key: str,
) -> str:
    messages: List[Dict[str, str]] = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message},
    ]

    payload = _build_payload(model, messages, temperature)

    try:
        body = _post_chat_completions(base_url, api_key, payload, timeout_seconds=60.0)
        return _extract_message_content(body)
    except requests.Timeout:
        raise Exception("Request timed out")
    except requests.HTTPError as http_err:
        status = http_err.response.status_code if http_err.response is not None else "unknown"
        error_msg = ""
        try:
            err_json = http_err.response.json() if http_err.response is not None else {}
            error_msg = err_json.get("error", {}).get("message", "")
        except Exception:
            try:
                error_msg = http_err.response.text[:300] if http_err.response is not None else ""
            except Exception:
                error_msg = ""
        raise Exception(f"HTTP {status}: {error_msg}")
    except requests.RequestException as req_err:
        raise Exception(f"Network error: {req_err}")
    except json.JSONDecodeError:
        raise Exception("Invalid JSON response from server")


def _parse_json_response(response: str) -> Dict[str, Any]:
    response = response.strip()
    if response.startswith("```json"):
        response = response[7:]
    if response.startswith("```"):
        response = response[3:]
    if response.endswith("```"):
        response = response[:-3]
    response = response.strip()

    try:
        return json.loads(response)
    except json.JSONDecodeError as e:
        raise Exception(f"Failed to parse JSON response: {e}\nResponse: {response[:500]}")


def generate_code(task_description: str, model: str, base_url: str, api_key: str) -> Dict[str, str]:
    console.print(f"[cyan]Agent 1 (Code Generator)[/cyan] - Generating code for: {task_description}")

    user_message = f"Generate Python code for the following task:\n\n{task_description}"

    response = _call_agent(
        system_prompt=AGENT1_SYSTEM_PROMPT,
        user_message=user_message,
        temperature=0.7,
        model=model,
        base_url=base_url,
        api_key=api_key,
    )

    try:
        result = _parse_json_response(response)
        if "code" not in result or "explanation" not in result or "task_description" not in result:
            raise Exception("Missing required fields in Agent 1 response")
        return {
            "code": result["code"],
            "explanation": result["explanation"],
            "task_description": result["task_description"],
        }
    except Exception as e:
        console.print(f"[red]Error parsing Agent 1 response: {e}[/red]")
        raise


def validate_and_improve_code(
    code_data: Dict[str, str],
    model: str,
    base_url: str,
    api_key: str,
) -> Dict[str, Any]:
    console.print(f"[green]Agent 2 (Code Validator/Improver)[/green] - Reviewing code...")

    user_message = (
        f"Review and improve the following code:\n\n"
        f"Task Description: {code_data['task_description']}\n"
        f"Explanation: {code_data['explanation']}\n"
        f"Code:\n{code_data['code']}\n\n"
        f"Please validate this code and provide an improved version."
    )

    response = _call_agent(
        system_prompt=AGENT2_SYSTEM_PROMPT,
        user_message=user_message,
        temperature=0.0,
        model=model,
        base_url=base_url,
        api_key=api_key,
    )

    try:
        result = _parse_json_response(response)
        required_fields = ["is_valid", "issues", "improved_code", "improvements", "validation_notes"]
        for field in required_fields:
            if field not in result:
                raise Exception(f"Missing required field: {field}")
        return result
    except Exception as e:
        console.print(f"[red]Error parsing Agent 2 response: {e}[/red]")
        raise


def display_agent1_output(code_data: Dict[str, str]) -> None:
    console.print()
    console.rule("[bold cyan]Agent 1 Output - Generated Code[/bold cyan]")
    console.print()

    console.print(f"[bold]Task:[/bold] {code_data['task_description']}")
    console.print()
    console.print(f"[bold]Explanation:[/bold] {code_data['explanation']}")
    console.print()

    code_md = Markdown(f"```python\n{code_data['code']}\n```", code_theme="monokai")
    console.print(Panel(code_md, border_style="cyan", title="Generated Code"))


def display_agent2_output(validation_result: Dict[str, Any]) -> None:
    console.print()
    console.rule("[bold green]Agent 2 Output - Validation & Improvements[/bold green]")
    console.print()

    status_color = "green" if validation_result["is_valid"] else "yellow"
    status_text = "Valid" if validation_result["is_valid"] else "Issues Found"
    console.print(f"[bold]Validation Status:[/bold] [{status_color}]{status_text}[/{status_color}]")
    console.print()

    if validation_result["issues"]:
        console.print("[bold]Issues Found:[/bold]")
        for issue in validation_result["issues"]:
            console.print(f"  • {issue}")
        console.print()

    if validation_result["improvements"]:
        console.print("[bold]Improvements Made:[/bold]")
        for improvement in validation_result["improvements"]:
            console.print(f"  • {improvement}")
        console.print()

    console.print("[bold]Validation Notes:[/bold]")
    notes_md = Markdown(validation_result["validation_notes"], code_theme="monokai")
    console.print(Panel(notes_md, border_style="green", title="Detailed Notes"))
    console.print()

    improved_code_md = Markdown(f"```python\n{validation_result['improved_code']}\n```", code_theme="monokai")
    console.print(Panel(improved_code_md, border_style="green", title="Improved Code"))


def display_comparison(code_data: Dict[str, str], validation_result: Dict[str, Any]) -> None:
    console.print()
    console.rule("[bold yellow]Code Comparison[/bold yellow]")
    console.print()

    comparison_table = Table(show_header=True, header_style="bold magenta")
    comparison_table.add_column("Aspect", style="cyan")
    comparison_table.add_column("Original (Agent 1)", style="white")
    comparison_table.add_column("Improved (Agent 2)", style="white")

    original_lines = len(code_data["code"].split("\n"))
    improved_lines = len(validation_result["improved_code"].split("\n"))

    comparison_table.add_row("Lines of Code", str(original_lines), str(improved_lines))
    comparison_table.add_row("Validation Status", "N/A", "Valid" if validation_result["is_valid"] else "Issues Found")
    comparison_table.add_row("Issues Found", "N/A", str(len(validation_result["issues"])))
    comparison_table.add_row("Improvements", "N/A", str(len(validation_result["improvements"])))

    console.print(comparison_table)
    console.print()


def run() -> None:
    api_key = settings.openai_api_key
    if not api_key:
        console.print("[red]OPENAI_API_KEY is not set. Add it to your .env and try again.[/red]")
        return

    base_url = _get_base_url()
    model = settings.openai_model

    console.print("[bold cyan]Day 6 — Subagents Interaction[/bold cyan]")
    console.print()
    console.print("[dim]This demonstration shows two interacting agents:[/dim]")
    console.print("[dim]  • Agent 1 (Code Generator): Generates Python code with temperature 0.7[/dim]")
    console.print("[dim]  • Agent 2 (Validator/Improver): Validates and improves code with temperature 0.0[/dim]")
    console.print()
    console.print(f"[dim]Model:[/dim] {model}  [dim]Base URL:[/dim] {base_url}")
    console.print()

    task_description = "Write a function to calculate the factorial of a non-negative integer. Include proper error handling."

    try:
        code_data = generate_code(task_description, model, base_url, api_key)
        display_agent1_output(code_data)

        validation_result = validate_and_improve_code(code_data, model, base_url, api_key)
        display_agent2_output(validation_result)

        display_comparison(code_data, validation_result)

        console.print("[green]✓ Subagent interaction completed successfully![/green]")

    except Exception as e:
        console.print(f"[red]Error during subagent interaction: {e}[/red]")

